# Comando para correr la base de datos de desarrollo: 
# docker compose up -d

services:
  # Base de datos de DESARROLLO
  db:
    image: postgres:16
    container_name: poc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: poc_user
      POSTGRES_PASSWORD: poc_pass
      POSTGRES_DB: poc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # ‚Üê Sin :ro para evitar problemas de permisos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poc_user -d poc_db"]
      interval: 2s
      timeout: 3s
      retries: 20

volumes:
  pgdata: